In [39]:
import pandas as pd


from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
import os
import re
import yfinance as yf

#from model.models import *
#import data.preprocessing as pp
import sys; sys.path.insert(0, '..')
import data.preprocessing as pp
from env.BaseEnv import EnvConfig
from agents.Base.BaseAgent import *
from agents.BlueAgents import DRLAgent
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
from env.EnvStock_train import StockEnvTrain

In [12]:
data = pd.read_csv('../datasets/downew30.csv')

In [37]:
ppo = AgentPPO()

In [76]:
indata = pp.data_split(data,'2013-01-01','2013-04-04')
env  = DummyVecEnv([lambda : StockEnvTrain(
    indata, indata, 30, EnvConfig, time_window =15
)])

1563


In [86]:
agent_build = DRLAgent(StockEnvTrain, indata, EnvConfig)

In [90]:
agent = agent_build.get_model('ppo',None)

603


In [91]:
agent

In [77]:
actions = np.random.uniform(-1, 1, 30)

In [78]:
actions

array([-0.18632703, -0.01042103, -0.59960036,  0.61364556, -0.60242163,
       -0.64759275,  0.85454326,  0.54107127,  0.55500726, -0.06891235,
        0.3156528 , -0.07573323, -0.4114394 ,  0.41519705, -0.34106799,
        0.74488816,  0.39287515, -0.86524568,  0.59369842, -0.40105567,
       -0.09035213, -0.5350953 , -0.97630373, -0.86624721, -0.60776463,
       -0.61272962,  0.52271025,  0.25999591,  0.06211608, -0.63435951])

In [79]:
env.step([actions])

(array([[9.6395562e+05, 1.3588820e+01, 5.2394886e+01, ..., 1.1090600e+07,
         1.0000000e+00, 2.5000000e+01]], dtype=float32),
 array([-5.8479314], dtype=float32),
 array([False]),
 [{}])

In [71]:
633 *3

1899

In [6]:
df = pd.read_csv('agents_hparams.csv')

In [8]:
df = df[df.model_name=='WarrenBuffer-v0.2']

In [11]:
new_hparams = {k.split(':')[0]:k.split(':')[1] for k in df.loc[81, 'hparams'].split(',')}

In [12]:
new_hparams

{'gamma': '0.999',
 'ent_coef': '1.005774650265196',
 'cliprange': '0.4',
 'lam': '0.92',
 'max_grad_norm': '0.9',
 'vf_coef': '0.2576995665520915',
 'learning_rate': '<bound method LinearSchedule.value of <stable_baselines.common.schedules.LinearSchedule object at 0x000001EFABD6B388>>'}

In [7]:
pp = PPO2('MlpPolicy',env='CartPole-v1')





Instructions for updating:
Use keras.layers.flatten instead.
Instructions for updating:
Please use `layer.__call__` method instead.





Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where





In [13]:
pp.get_parameters()

OrderedDict([('model/pi_fc0/w:0',
              array([[ 0.01894654,  0.332925  ,  0.08375002,  0.0937167 , -0.02585774,
                      -0.15916517,  0.00401111, -0.01784066,  0.33241567,  0.099254  ,
                       0.29362324,  0.10271958,  0.23773494, -0.18088374, -0.32294095,
                       0.24043858,  0.12667677, -0.27742547, -0.03133523, -0.15709531,
                      -0.13729842,  0.00192487, -0.12728044,  0.16087772,  0.24032906,
                       0.05223167,  0.15738286,  0.06826203,  0.05862476,  0.06356401,
                       0.1539644 , -0.15193573, -0.20010446,  0.1351151 , -0.13466366,
                       0.05389585,  0.06425314,  0.11113809, -0.23354442,  0.00669265,
                      -0.00684502,  0.14955083, -0.05520641,  0.20388867,  0.16432351,
                       0.22460277,  0.367134  , -0.0294769 ,  0.03534558,  0.08927404,
                       0.0756272 , -0.2715011 , -0.16316636, -0.41902828,  0.49809408,
         